### PR TITLE
Awesome Books: First Proyect

### PR DESCRIPTION
**Pull request by maximoortelli**
_Awesome Books is an exercise in which I will build a basic website that allows users to add/remove books from a list. I will achieve that by using JavaScript objects and arrays. I will also need to dynamically modify the DOM and add basic events. The goal here is to master all of the tools and best practices learned about in previous steps to use them in all Microverse projects and most likely in my future job as well._

### CODE REVIEW

**Review by shella12 — COMMENTED** [review]
Hi @maximoortelli, 

#  Status: Invalidated :red_circle: 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

This milestone is a pair-programming activity. Please make sure all your partners contribute to your project (must be a valid contribution not README editing) before submitting another request

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @maximoortelli, @danielf-canon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request

This milestone is a collaborative pair-programming activity, designed to showcase teamwork and shared contributions. It's essential that all team members actively participate and contribute valid code to the project. Currently, I see that both "Maximo Ortelli Rueda" and "Daniel Cañón Sanchez" have done a commendable job in their contributions. However, there's also another team member, "Bouhmid Ben Jmii," who hasn't yet made a valid contribution.

To ensure the successful completion of this milestone, I recommend that all three of you come together to actively collaborate on the project. It's crucial that each team member is involved in the development process and contributes substantial code to the project.

If you're facing any challenges or difficulties with collaboration, I suggest reaching out to your partners first to resolve any issues. If the collaboration issues persist, don't hesitate to contact the Student Success Team for assistance. They are here to help and ensure that your team's collaboration is successful.

Remember, effective teamwork is a key component of this milestone, and the goal is to create a project where each team member's contributions are clearly reflected. Keep up the good work, and I'm confident you'll be able to collaborate effectively and complete the milestone together! 🌟👥🚀"

## 🔴🚫Attention🚫🔴 

📢 Your Code Review Request will be marked as invalid🚫 in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        GitHub
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        LinkedIn
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        Slack
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        Email
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_**📢💡Invalid Code Review Request **does not count** into the code reviews limit.💡**_

**Comment by maximoortelli** [comment]
Hi @shahadat3669 the coding buddy you mentioned above Bouhmid Ben Jmii is not active, he is not connecting to meetings nor did he send us a message. Now we communicate with Student Succes so as not to waste time with the projects.

**Review by shahadat3669 — CHANGES_REQUESTED** [review]
Hi @maximoortelli, @danielf-canon, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.



## Invalid Code Review Request
- [ ] As I mentioned earlier, I recommend that all three of you come together to actively collaborate on the project. It's crucial that each team member is involved in the development process and contributes substantial code to the project. Since you've mentioned that you've contacted the student success team for assistance, I understand that you're taking steps to address any collaboration issues. Please be patient and wait for their response, as they will be able to guide you on how to best resolve the situation. 

Remember, successful teamwork is essential to creating a well-rounded project. Keep up the effort! 🌟👥🚀

## 🔴🚫Attention🚫🔴 

📢 Your Code Review Request will be marked as invalid🚫 in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

## Have any doubt ❓

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

<table width="100%" align="center">
  <tr>
    <td colspan="4" align="center">
      <strong>Contact me: Shahadat Hossain</strong>
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://github.com/shahadata3669">
        GitHub
      </a>
    </td>
    <td align="center">
      <a href="https://www.linkedin.com/in/shahadat-cseng/">
        LinkedIn
      </a>
    </td>
    <td align="center">
      <a href="https://app.slack.com/client/T47CT8XPG/D05GT4E4WAY/rimeto_profile/U04426SD71V">
        Slack
      </a>
    </td>
    <td align="center">
      <a href="mailto:shahadat3669@gmail.com?subject=Microverse%20Code%20Review">
        Email
      </a>
    </td>
  </tr>
</table>

## ⚠️ WARNING ⚠️

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_**📢💡Invalid Code Review Request **does not count** into the code reviews limit.💡**_

**Comment by maximoortelli** [comment]
_Maximo and Daniel Felipe has been given permission to continue this week without their third partner. Please don't invalidate their pull requests if it does not have commits from their 3rd partner Ahmed, if you have any doubts please contact Marco from the Student Success team via the Code Reviewers Slack Workspace._

**Review by BregornOriginal — APPROVED** [review]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it 

Congratulations! 

giphy (7)

## Highlights

✅ Linters are passing
✅ Good commit history
✅ Good work implementing methods for Books

[OPTIONAL] I would like to give you a tip for this project and for your entire coding career. It's an excellent and useful practice to write CLEAN and DRY code, this means that try to use pure functions every time that you can. In this project, it would be great to use different functions for each method that you are needing. For example, one function is for deleting, the other for showing and the other for adding books. So you call them wherever you need them.

## Optional suggestions
Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application.
Cheers and Happy coding!:aplauso::aplauso::aplauso:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

Please, remember to tag me in your question so I can receive the notification.
------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)[.](https://airtable.com/shrQAqnBwek5a0O0s)._)

**Pull request merged**
